<?php

/**
 * @file
 * URL property behavior for eck, web url link.
 */

$plugin = array(
  'label' => t('URL'),
  'default_widget' => 'eck_extras_url_property_default_widget',
  'default_formatter' => 'eck_extras_url_property_default_formatter',
);

function eck_extras_url_property_default_widget($property, $vars) {
  
}

function eck_extras_url_property_default_formatter($property, $vars) {
  
}
